@startuml


abstract class Участник
class Покупатель
class Продавец
class Администратор

hide empty members

class Продавец {
Продажа()
}

class Покупатель {
Покупка()
}

class Администратор {
Проверка()
}

class Ставка{
}

class Предложение{
}

class Сделка

package Каталог <<Database>>{

hide empty members

entity Лот{
**id_лот**
наименование
}

entity Вещь{
**id_вещь**
//id_лот//
размер
}

entity Ставк_а{
**id_пользователя**
//id_вещь//
ставка
}


entity Предложени_е{
**id_пользователя**
//id_вещь//
предложение
}


}


Лот  ||--o{ Вещь

Вещь  ||--o{ Ставк_а
Вещь  ||--o{ Предложени_е

Покупатель -|> Участник
Администратор -|> Участник
Продавец -|> Участник


Администратор "1" <-  "1" Сделка

Покупатель "1" o-- "0..n" Ставка
Продавец "1" o-- "0..n" Предложение

Сделка "1" -> "1" Ставка
Предложение"1" <- "1" Сделка

'note left of Ставк_а: Проверка при добавлении ставки/предложения\n на "моментальную" покупку (bet == ask)

@enduml