@startuml

left to right direction

(Продажа товара) as (Продажа)
(Отправка товара) as (Отправить)
(Получение товара) as (Принять)
Продажа <|-- (Моментальная продажа)
Продажа <|-- (Создание лота)


Продавец --> (Продажа)
Продавец --> (Отправить)
Продавец --> (Принять)

newpage

left to right direction

(Получение товара) as (Принять)
(Проверка товара) as (Проверка)
(Отправка товара) as (Отправить)



Администратор--> (Принять)
Администратор --> (Отправить)
Администратор --> (Проверка)

newpage

left to right direction

(Покупка товара) as (Покупка)
(Получение товара) as (Получить)
(Возврат товара) as (Возврат)

Покупка <|-- (Моментальная покупка)
Покупка <|-- (Размещение ставки)

Покупатель--> (Покупка)
Покупатель--> (Получить)
Покупатель --> (Возврат)

@enduml